### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by mattsoup** [nebiolabs/ampseer#6]
After running cargo test:

running 10 tests
test test_cli ... ok
test test_help_exit_code ... ok
test missing_reads ... ok
test ont_amps_find_both_orientations ... FAILED
test differentiate_artic_v3_from_vss ... FAILED
test test_version ... ok
test test_insufficient_arguments ... ok
test non_matching_primer_sets ... ok
test differentiate_vss_from_artic_v3 ... ok
test differentiate_vss2_from_vss1a ... FAILED

failures:

---- ont_amps_find_both_orientations stdout ----
thread 'ont_amps_find_both_orientations' panicked at 'Unexpected stdout, failed fn(var)
└── var as str: 

command=`"/Users/mcampbell/Desktop/src/ampseer/target/debug/ampseer" "--primer-sets" "/Users/mcampbell/Desktop/src/ampseer/tests/fixtures/vss_18_28.bed.fasta" "--reads" "/Users/mcampbell/Desktop/src/ampseer/tests/fixtures/ont_vss_full_length_amp18rev_amp28for.fastq"`
code=1
stdout=""
stderr="2022-01-25 17:12:39,767 ERROR [ampseer] Could not find reads at \"/Users/mcampbell/Desktop/src/ampseer/tests/fixtures/ont_vss_full_length_amp18rev_amp28for.fastq\"\nError: Invalid input\n"
', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- differentiate_artic_v3_from_vss stdout ----
thread 'differentiate_artic_v3_from_vss' panicked at 'Unexpected stdout, failed fn(var)
└── var as str: 

command=`"/Users/mcampbell/Desktop/src/ampseer/target/debug/ampseer" "--primer-sets" "/Users/mcampbell/Desktop/src/ampseer/tests/fixtures/primer_sets/ARTIC_v3.bed.fasta" "/Users/mcampbell/Desktop/src/ampseer/tests/fixtures/primer_sets/neb_vss1a.bed.fasta" "--reads" "/Users/mcampbell/Desktop/src/ampseer/tests/fixtures/artic_v3.fastq"`
code=1
stdout=""
stderr="2022-01-25 17:12:39,767 ERROR [ampseer] Could not find reads at \"/Users/mcampbell/Desktop/src/ampseer/tests/fixtures/artic_v3.fastq\"\nError: Invalid input\n"
', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5

---- differentiate_vss2_from_vss1a stdout ----
thread 'differentiate_vss2_from_vss1a' panicked at 'Unexpected stdout, failed fn(var)
└── var as str: unknown

**Comment by bwlang** [comment]
fixed in  64d8a7bc728543a6b88b2524c5e4c8a3ddec194d
